### ISSUE TITLE
UPF startup delayed ~15 minutes

### ISSUE THREAD

**Issue by markbeierl** [canonical/sdcore-upf-operator#47]
As the UPF is deployed, the charm reconfigures multus to have the additional network attachment definitions, and then restarts the pod.  There seems to be an error preventing the charm from restarting as the following error is seen repeatedly in the juju debug log, and the pod stays in `terminating` state
```
unit-upf-0: 17:08:30 ERROR juju.worker.uniter.operation hook "stop" (via hook dispatching script: dispatch) failed: exit status 1
unit-upf-0: 17:08:30 WARNING unit.upf/0.juju-log 2 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-upf-0: 17:08:30 INFO unit.upf/0.juju-log HTTP Request: GET https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/user-plane/network-attachment-definitions "HTTP/1.1 401 Unauthorized"
unit-upf-0: 17:08:30 ERROR unit.upf/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/lightkube/core/generic_client.py", line 188, in raise_for_status
    resp.raise_for_status()
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://10.152.183.1/apis/k8s.cni.cncf.io/v1/namespaces/user-plane/network-attachment-definitions'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-upf-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 292, in list_network_attachment_definitions
    return list(
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/lightkube/core/generic_client.py", line 252, in list
    cont, chunk = self.handle_response('list', resp, br)
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/lightkube/core/generic_client.py", line 196, in handle_response
    self.raise_for_status(resp)
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/lightkube/core/generic_client.py", line 190, in raise_for_status
    raise transform_exception(e)
lightkube.core.exceptions.ApiError: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-upf-0/charm/./src/charm.py", line 961, in <module>
    main(UPFOperatorCharm)
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/ops/main.py", line 439, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/ops/framework.py", line 849, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-upf-0/charm/./src/charm.py", line 356, in _on_config_changed
    self.on.nad_config_changed.emit()
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-upf-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-upf-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 533, in _configure_multus
    self._configure_network_attachment_definitions()
  File "/var/lib/juju/agents/unit-upf-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 572, in _configure_network_attachment_definitions
    ) in self.kubernetes.list_network_attachment_definitions():
  File "/var/lib/juju/agents/unit-upf-0/charm/lib/charms/kubernetes_charm_libraries/v0/multus.py", line 296, in list_network_attachment_definitions
    raise KubernetesMultusError("Could not list NetworkAttachmentDefinitions")
charms.kubernetes_charm_libraries.v0.multus.KubernetesMultusError: Could not list NetworkAttachmentDefinitions
```

This message is repeated every 1 second for ~15 minutes.  It appears that something in Juju or K8s gives up at this point and the charm is forcefully restarted.  Once that happens, it is able to proceed with creating the NetworkAttachmentDefinitions and it starts up normally

**Comment by ghislainbourgeois** [comment]
Fixed by #49
